### ISSUE TITLE
转账数据延时

### ISSUE THREAD

**Issue by spinshine** [WanxiangBlockchainLabs/OpenAPI#1]
转账之后，大概需要20秒到几分钟的延时。 如果是设定如此，请忽略。

**Comment by lrwx** [comment]
底层架构如此。除非切换成另一套账本。
可忽略此issue

**Comment by AndyDuan** [comment]
转账数据延时具体指的是转账开始到转账成功的延时，还是说转账开始到交易记录显示之间的延时呢？

**Comment by spinshine** [comment]
是转账成功以后，到交易记录之间的延时。

**Comment by AndyDuan** [comment]
这是现在的底层区块链的特性决定的。第一个是由分布式网络的节点之间的同步会有延迟。 第二个是由区块链的共识算法决定数据最终被记录到链上会有延迟。平均延时应该是在20秒左右。
