### ISSUE TITLE
转账接口报错

### ISSUE THREAD

**Issue by spinshine** [WanxiangBlockchainLabs/OpenAPI#10]
![qq 20160929093744](https://cloud.githubusercontent.com/assets/3784505/18938076/7b1bb9f0-8628-11e6-8b05-342f2cdd6591.png)

**Comment by spinshine** [comment]
由于前一天调试，header设置错误。
代码 /functions/request.js    line:10
'application/json;charset=utf-8';

**Comment by AndyDuan** [comment]
Andy 测试无问题。关闭issue。
