### ISSUE TITLE
交易记录

### ISSUE THREAD

**Issue by spinshine** [WanxiangBlockchainLabs/OpenAPI#6]
1 无法获取交易记录
   测试address: 0xd468a1f3e197692711be7ac86b828ba24cb10fee
2 最多只能获取9条交易记录

**Comment by Swarmxcy** [comment]
exitThread里显示进度的代码在服务器上会产生bug，已清楚。

**Comment by Swarmxcy** [comment]
Web3Wallet.js 行721: 给spaces一个“”。

**Comment by AndyDuan** [comment]
仍然有问题，交易记录完全无法显示出来。已确认原因是JSON.parse抛出异常。

**Comment by spinshine** [comment]
http在chunk模式下，数据分段。 接收数据不完整导致json解析失败。
现在拼装完整，可以解析了。

**Comment by AndyDuan** [comment]
Andy测试可以正常显示。关闭此Issue。
